/**
 * Build an installable Design Contract pack compatible with
 * https://github.com/byronwade/Design
 *
 * Authored façade (what users download / drop into a project):
 *   DESIGN.md
 *   AGENTS.md
 *   .agents/skills/design/SKILL.md
 *   design/references/manifest.json
 *   design/REFERENCES.md
 *   .design/config.json
 *   INSTALL.md
 *   contract.json  (scan provenance metadata)
 */

import { zipSync, strToU8 } from 'fflate'
import {
  generateDesignMd,
  type DesignMdInput,
  type DesignMdArtifact,
} from '@/lib/analyzers/design-md-generator'
import { generateDesignSkill } from '@/lib/analyzers/design-skill-generator'

export type DesignContractPackageInput = DesignMdInput & {
  scanId?: string
  profile?: 'web-app' | 'web-marketing'
  appType?: string
  screenshots?: Array<{
    label: string
    url?: string
    note?: string
  }>
}

export type DesignContractFile = {
  path: string
  content: string
}

export type DesignContractPackage = {
  slug: string
  title: string
  domain: string
  profile: 'web-app' | 'web-marketing'
  files: DesignContractFile[]
  designMd: DesignMdArtifact
  installCommand: string
  summary: {
    colorCount: number
    typographyCount: number
    spacingCount: number
    fileCount: number
  }
}

function slugify(domain: string): string {
  return domain
    .toLowerCase()
    .replace(/^www\./, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}

function agentsMd(domain: string): string {
  return `# Product design and UI engineering

This repository uses a compiled design contract extracted from **${domain}** via Design Contracts.

The managed instructions below are the minimum routing surface for AI agents; project-specific instructions may be added outside the managed block.

<!-- design-contract:managed:start -->
## Required agent workflow

1. Run \`npx --yes github:byronwade/Design status\`.
2. Run \`npx --yes github:byronwade/Design resolve --request "<task>"\`.
3. Read \`DESIGN.md\` and only the returned task packet under \`.design/generated/TASK.json\`.
4. Use the universal design Skill at \`.agents/skills/design/SKILL.md\`.
5. Inspect production components, routes, tests, and applicable files under \`design/references/\`.
6. Build with semantic tokens and mapped components from \`DESIGN.md\`. Missing capability is a design-system gap — do not invent page-local styles.
7. Run \`npx --yes github:byronwade/Design check\`.
8. Run \`npx --yes github:byronwade/Design verify --mode release\` with evidence for affected surfaces.
9. Report the receipt path, revision, warnings, and remaining uncertainty.

## Boundaries

- \`DESIGN.md\` is the authored source of truth for visual identity and product grammar.
- Do not edit \`.design/generated/\` or \`.design/receipts/\` by hand.
- Visual references under \`design/references/\` are optional project-owned media.
- Scan-derived tokens seeded this contract; promote gaps intentionally after review.
<!-- design-contract:managed:end -->
`
}

function universalDesignSkill(): string {
  return `---
name: design
description: Resolve, apply, check, and verify the project DESIGN.md grammar before UI work.
---

# Design

Use this Skill for UI, component, layout, content-state, visual-reference, motion,
or design-system changes. It is the universal adapter across agents.

## Workflow

1. Run \`npx --yes github:byronwade/Design status\`.
2. Run \`npx --yes github:byronwade/Design resolve --request "<task>"\`.
3. Read the returned task model, relevant components, tokens, patterns,
   selected references, constraints, and checks. Do not load the full engine or
   full reference library unless the packet points to a specific source.
4. Inspect production code, variants, stories, tests, fixtures, routes, and
   applicable approved files under \`design/references/\`.
5. Build with semantic tokens and mapped production components. A missing
   capability is a design-system gap, not permission for page-local styling.
6. Run \`npx --yes github:byronwade/Design check\`.
7. Run \`npx --yes github:byronwade/Design verify --mode release\` with the
   affected surfaces and evidence files.
8. Report the receipt path, source revision, warnings, exceptions, and remaining
   uncertainty.

## Boundaries

- \`DESIGN.md\` is the authored source of truth.
- Generated context, receipts, adapters, schemas, caches, and fingerprints are not
  authored design truth.
- Component libraries are optional adapters.
- Visual references are project-owned and optional.
- Do not claim completion without a fresh design receipt.
`
}

function installMd(domain: string, profile: string): string {
  return `# Install this Design Contract

This pack was generated by **Design Contracts** from \`${domain}\`.

It is compatible with the open-source Design Contract engine:
https://github.com/byronwade/Design

## Fast path (drop-in)

1. Copy \`DESIGN.md\` to your project root (or merge tokens into an existing one).
2. Copy \`.agents/skills/design/SKILL.md\` into your project.
3. Copy \`AGENTS.md\` (or merge the managed block into your existing agent instructions).
4. Optionally copy \`design/references/\`.

Then install the engine adapters:

\`\`\`bash
npx --yes github:byronwade/Design init --profile ${profile}
\`\`\`

If \`DESIGN.md\` already exists, the installer keeps your authored file and generates the hidden enforcement engine under \`.design/\`.

## Enforce forever

\`\`\`bash
npx --yes github:byronwade/Design resolve --request "Add a settings page"
npx --yes github:byronwade/Design check
npx --yes github:byronwade/Design verify --mode release --surface settings --evidence path/to/evidence.html
\`\`\`

Any new component your agent adds should resolve against this contract, get checked for raw values / unmapped styles, and verify with a receipt — so the design holds over time.

## Cursor / Claude

Point project rules at \`DESIGN.md\` and the \`design\` skill before generating UI. Do not invent colors, type, spacing, or radii outside the YAML front matter.
`
}

function referencesMd(domain: string, screenshots: DesignContractPackageInput['screenshots']): string {
  const lines = [
    '---',
    'kind: visual-references',
    'status: project-owned',
    '---',
    '',
    '# Visual references',
    '',
    `Approved visual memory for the **${domain}** design contract.`,
    '',
    'Register why each reference matters, where it applies, what to preserve, and what not to copy.',
    'External scan observations seed drift evidence; they never replace `DESIGN.md` automatically.',
    '',
  ]

  if (screenshots?.length) {
    lines.push('## Captured surfaces', '')
    for (const shot of screenshots) {
      lines.push(`### ${shot.label}`)
      if (shot.url) lines.push(`- Source: ${shot.url}`)
      lines.push(`- Note: ${shot.note || 'Preserve hierarchy, density, and material — do not copy pixel-perfect chrome.'}`)
      lines.push('')
    }
  } else {
    lines.push(
      '## Getting started',
      '',
      'Add screenshots, golden states, or Mobbin-style pattern notes under `design/references/` and register them in `manifest.json`.',
      'A project can start with zero references; missing references do not block adoption.',
      ''
    )
  }

  return lines.join('\n')
}

function referencesManifest(
  domain: string,
  url: string,
  screenshots: DesignContractPackageInput['screenshots']
): string {
  const refs = (screenshots ?? []).map((shot, index) => ({
    id: `scan-surface-${index + 1}`,
    kind: 'screenshot',
    label: shot.label,
    source: shot.url || url,
    ownership: 'scan-derived',
    license: 'public-web-observation',
    platform: 'web',
    surface: shot.label,
    confidence: 0.7,
    relevance: ['visual-identity', 'layout', 'density'],
    preserve: ['hierarchy', 'spacing rhythm', 'accent scarcity', 'typography roles'],
    doNotCopy: ['pixel-perfect chrome', 'copyrighted illustrations', 'product copy'],
    note: shot.note || null,
  }))

  return `${JSON.stringify(
    {
      schemaVersion: 1,
      domain,
      sourceUrl: url,
      policy:
        'Resolver selects 3-8 approved references by request, platform, component, state, confidence, and relevance.',
      references: refs,
    },
    null,
    2
  )}\n`
}

function configJson(profile: string, appType?: string): string {
  return `${JSON.stringify(
    {
      $schema:
        'https://raw.githubusercontent.com/byronwade/Design/main/schemas/config.schema.json',
      schemaVersion: 1,
      targets: [
        {
          id: profile,
          profile,
          root: '.',
          default: true,
          ...(appType ? { appType } : {}),
          overrides: [],
        },
      ],
      overrides: [],
      adapters: ['codex', 'claude', 'copilot', 'cursor'],
    },
    null,
    2
  )}\n`
}

export function buildDesignContractPackage(
  input: DesignContractPackageInput
): DesignContractPackage {
  const profile = input.profile ?? 'web-marketing'
  const domain = input.domain.replace(/^www\./, '')
  const slug = slugify(domain)
  const designMd = generateDesignMd(input)
  const siteSkill = generateDesignSkill({
    domain,
    url: input.url,
    designMdFileName: 'DESIGN.md',
    curatedTokens: input.curatedTokens,
    personality: input.brandAnalysis?.personality,
  })

  const files: DesignContractFile[] = [
    { path: 'DESIGN.md', content: designMd.markdown },
    { path: 'AGENTS.md', content: agentsMd(domain) },
    { path: 'INSTALL.md', content: installMd(domain, profile) },
    { path: '.agents/skills/design/SKILL.md', content: universalDesignSkill() },
    {
      path: `.agents/skills/${siteSkill.skillName}/SKILL.md`,
      content: siteSkill.markdown,
    },
    {
      path: 'design/REFERENCES.md',
      content: referencesMd(domain, input.screenshots),
    },
    {
      path: 'design/references/manifest.json',
      content: referencesManifest(domain, input.url, input.screenshots),
    },
    {
      path: 'design/references/.gitkeep',
      content: '',
    },
    { path: '.design/config.json', content: configJson(profile, input.appType) },
    {
      path: 'contract.json',
      content: `${JSON.stringify(
        {
          schemaVersion: 1,
          kind: 'design-contract-pack',
          slug,
          domain,
          sourceUrl: input.url,
          profile,
          appType: input.appType ?? null,
          scanId: input.scanId ?? null,
          generatedAt: new Date().toISOString(),
          engine: 'https://github.com/byronwade/Design',
          generator: 'design-contracts',
          files: [
            'DESIGN.md',
            'AGENTS.md',
            'INSTALL.md',
            '.agents/skills/design/SKILL.md',
            'design/references/manifest.json',
            '.design/config.json',
          ],
        },
        null,
        2
      )}\n`,
    },
  ]

  return {
    slug,
    title: `${domain} Design Contract`,
    domain,
    profile,
    files,
    designMd,
    installCommand: `npx --yes github:byronwade/Design init --profile ${profile}`,
    summary: {
      colorCount: designMd.summary.colorCount,
      typographyCount: designMd.summary.typographyCount,
      spacingCount: designMd.summary.spacingCount,
      fileCount: files.length,
    },
  }
}

export function zipDesignContractPackage(pack: DesignContractPackage): Uint8Array {
  const entries: Record<string, Uint8Array> = {}
  const root = `${pack.slug}-design-contract`
  for (const file of pack.files) {
    entries[`${root}/${file.path}`] = strToU8(file.content)
  }
  return zipSync(entries, { level: 6 })
}
